__author__ = "Mark Diamantino Caribé"
__copyright__ = "Copyright 2017-2018, Projet de fin d'année - ULB, B1-INFO"
from PyQt5 import QtCore, QtWidgets

class Ui_Dialog(QtWidgets.QWidget):
    def __init__(self, parent=None):
        QtWidgets.QWidget.__init__(self, parent=None)
        self.setupUi(self)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1225, 677)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.trainingsetbox = QtWidgets.QComboBox(Dialog)
        self.trainingsetbox.setObjectName("trainingsetbox")
        self.trainingsetbox.addItem("")
        self.trainingsetbox.addItem("")
        self.trainingsetbox.addItem("")
        self.gridLayout_2.addWidget(self.trainingsetbox, 0, 1, 1, 1)
        self.anothertestcheck = QtWidgets.QCheckBox(Dialog)
        self.anothertestcheck.setCheckable(True)
        self.anothertestcheck.setObjectName("anothertestcheck")
        self.gridLayout_2.addWidget(self.anothertestcheck, 1, 0, 1, 1)
        self.testsetbox = QtWidgets.QComboBox(Dialog)
        self.testsetbox.setEnabled(False)
        self.testsetbox.setEditable(False)
        self.testsetbox.setObjectName("testsetbox")
        self.testsetbox.addItem("")
        self.testsetbox.addItem("")
        self.testsetbox.addItem("")
        self.gridLayout_2.addWidget(self.testsetbox, 1, 1, 1, 1)
        self.datasetlabel = QtWidgets.QLabel(Dialog)
        self.datasetlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.datasetlabel.setObjectName("datasetlabel")
        self.gridLayout_2.addWidget(self.datasetlabel, 0, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.trainingtestlabel = QtWidgets.QLabel(Dialog)
        self.trainingtestlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.trainingtestlabel.setObjectName("trainingtestlabel")
        self.verticalLayout_7.addWidget(self.trainingtestlabel)
        self.trainingtestspinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.trainingtestspinbox.setDecimals(1)
        self.trainingtestspinbox.setMaximum(0.9)
        self.trainingtestspinbox.setSingleStep(0.1)
        self.trainingtestspinbox.setProperty("value", 0.8)
        self.trainingtestspinbox.setObjectName("trainingtestspinbox")
        self.verticalLayout_7.addWidget(self.trainingtestspinbox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.activationlabel = QtWidgets.QLabel(Dialog)
        self.activationlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.activationlabel.setObjectName("activationlabel")
        self.verticalLayout_5.addWidget(self.activationlabel)
        self.activationbox = QtWidgets.QComboBox(Dialog)
        self.activationbox.setObjectName("activationbox")
        self.activationbox.addItem("")
        self.activationbox.addItem("")
        self.activationbox.addItem("")
        self.activationbox.addItem("")
        self.verticalLayout_5.addWidget(self.activationbox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lratelabel = QtWidgets.QLabel(Dialog)
        self.lratelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lratelabel.setObjectName("lratelabel")
        self.verticalLayout_8.addWidget(self.lratelabel)
        self.lratespinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.lratespinbox.setDecimals(4)
        self.lratespinbox.setMinimum(0.0001)
        self.lratespinbox.setMaximum(0.1)
        self.lratespinbox.setSingleStep(0.0001)
        self.lratespinbox.setProperty("value", 0.0001)
        self.lratespinbox.setObjectName("lratespinbox")
        self.verticalLayout_8.addWidget(self.lratespinbox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.weightsinlabel = QtWidgets.QLabel(Dialog)
        self.weightsinlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.weightsinlabel.setObjectName("weightsinlabel")
        self.verticalLayout_15.addWidget(self.weightsinlabel)
        self.weightsinspinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.weightsinspinbox.setDecimals(4)
        self.weightsinspinbox.setMinimum(0.0001)
        self.weightsinspinbox.setMaximum(0.1)
        self.weightsinspinbox.setSingleStep(0.0001)
        self.weightsinspinbox.setProperty("value", 0.0001)
        self.weightsinspinbox.setObjectName("weightsinspinbox")
        self.verticalLayout_15.addWidget(self.weightsinspinbox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_15)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.hiddenlabel = QtWidgets.QLabel(Dialog)
        self.hiddenlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hiddenlabel.setObjectName("hiddenlabel")
        self.verticalLayout_9.addWidget(self.hiddenlabel)
        self.hiddenspinbox = QtWidgets.QSpinBox(Dialog)
        self.hiddenspinbox.setMinimum(10)
        self.hiddenspinbox.setMaximum(784)
        self.hiddenspinbox.setProperty("value", 50)
        self.hiddenspinbox.setObjectName("hiddenspinbox")
        self.verticalLayout_9.addWidget(self.hiddenspinbox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.crossvalabel = QtWidgets.QLabel(Dialog)
        self.crossvalabel.setAlignment(QtCore.Qt.AlignCenter)
        self.crossvalabel.setObjectName("crossvalabel")
        self.verticalLayout_10.addWidget(self.crossvalabel)
        self.crossvalspinbox = QtWidgets.QSpinBox(Dialog)
        self.crossvalspinbox.setMinimum(1)
        self.crossvalspinbox.setMaximum(100)
        self.crossvalspinbox.setProperty("value", 1)
        self.crossvalspinbox.setObjectName("crossvalspinbox")
        self.verticalLayout_10.addWidget(self.crossvalspinbox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.trainingepochslab = QtWidgets.QLabel(Dialog)
        self.trainingepochslab.setObjectName("trainingepochslab")
        self.verticalLayout_11.addWidget(self.trainingepochslab)
        self.trainingepochsspin = QtWidgets.QSpinBox(Dialog)
        self.trainingepochsspin.setMinimum(20)
        self.trainingepochsspin.setMaximum(1000)
        self.trainingepochsspin.setProperty("value", 50)
        self.trainingepochsspin.setObjectName("trainingepochsspin")
        self.verticalLayout_11.addWidget(self.trainingepochsspin)
        self.horizontalLayout_2.addLayout(self.verticalLayout_11)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.dodropcheck = QtWidgets.QCheckBox(Dialog)
        self.dodropcheck.setObjectName("dodropcheck")
        self.verticalLayout.addWidget(self.dodropcheck)
        self.dropurcentagespinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.dropurcentagespinbox.setEnabled(False)
        self.dropurcentagespinbox.setDecimals(1)
        self.dropurcentagespinbox.setMinimum(0.1)
        self.dropurcentagespinbox.setMaximum(0.9)
        self.dropurcentagespinbox.setSingleStep(0.1)
        self.dropurcentagespinbox.setProperty("value", 0.2)
        self.dropurcentagespinbox.setObjectName("dropurcentagespinbox")
        self.verticalLayout.addWidget(self.dropurcentagespinbox)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.saveweightscheck = QtWidgets.QCheckBox(Dialog)
        self.saveweightscheck.setObjectName("saveweightscheck")
        self.verticalLayout_6.addWidget(self.saveweightscheck)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadwegithsb = QtWidgets.QPushButton(Dialog)
        self.loadwegithsb.setObjectName("loadwegithsb")
        self.horizontalLayout.addWidget(self.loadwegithsb)
        self.weigtshloadedcheck = QtWidgets.QCheckBox(Dialog)
        self.weigtshloadedcheck.setText("Use them?")
        self.weigtshloadedcheck.setCheckable(False)
        self.weigtshloadedcheck.setObjectName("weigtshloadedcheck")
        self.horizontalLayout.addWidget(self.weigtshloadedcheck)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.startbutton = QtWidgets.QPushButton(Dialog)
        self.startbutton.setAutoDefault(True)
        self.startbutton.setDefault(False)
        self.startbutton.setFlat(False)
        self.startbutton.setObjectName("startbutton")
        self.verticalLayout_12.addWidget(self.startbutton)
        self.pausebutton = QtWidgets.QPushButton(Dialog)
        self.pausebutton.setObjectName("pausebutton")
        self.pausebutton.setEnabled(False)
        self.verticalLayout_12.addWidget(self.pausebutton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_12)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelivelogs = QtWidgets.QLabel(self.tab)
        self.labelivelogs.setObjectName("labelivelogs")
        self.gridLayout_3.addWidget(self.labelivelogs, 0, 0, 1, 1)
        self.logbrowser = QtWidgets.QTextBrowser(self.tab)
        self.logbrowser.setObjectName("logbrowser")
        self.logbrowser.setFontPointSize(11)
        self.gridLayout_3.addWidget(self.logbrowser, 2, 0, 1, 1)
        self.labelconfusionmat = QtWidgets.QLabel(self.tab)
        self.labelconfusionmat.setObjectName("labelconfusionmat")
        self.gridLayout_3.addWidget(self.labelconfusionmat, 0, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.savelogscheck = QtWidgets.QCheckBox(self.tab)
        self.savelogscheck.setObjectName("savelogscheck")
        self.horizontalLayout_5.addWidget(self.savelogscheck)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.qrgridLayout = QtWidgets.QGridLayout()
        self.qrgridLayout.setObjectName("qrgridLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.ocrdigitspinbox = QtWidgets.QSpinBox(self.tab_3)
        self.ocrdigitspinbox.setMinimum(1)
        self.ocrdigitspinbox.setMaximum(50)
        self.ocrdigitspinbox.setObjectName("ocrdigitspinbox")
        self.gridLayout_5.addWidget(self.ocrdigitspinbox, 1, 2, 1, 1)
        self.ocruploadpushbutton = QtWidgets.QPushButton(self.tab_3)
        self.ocruploadpushbutton.setObjectName("ocruploadpushbutton")
        self.gridLayout_5.addWidget(self.ocruploadpushbutton, 0, 6, 1, 1)
        self.startocrpushbutton = QtWidgets.QPushButton(self.tab_3)
        self.startocrpushbutton.setIconSize(QtCore.QSize(16, 16))
        self.startocrpushbutton.setObjectName("startocrpushbutton")
        self.gridLayout_5.addWidget(self.startocrpushbutton, 1, 6, 1, 1)
        self.ocrndigilabel = QtWidgets.QLabel(self.tab_3)
        self.ocrndigilabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ocrndigilabel.setObjectName("ocrndigilabel")
        self.gridLayout_5.addWidget(self.ocrndigilabel, 0, 2, 1, 1)
        self.ocrmodelabel = QtWidgets.QLabel(self.tab_3)
        self.ocrmodelabel.setObjectName("ocrmodelabel")
        self.gridLayout_5.addWidget(self.ocrmodelabel, 0, 5, 1, 1)
        self.ocrmodecombo = QtWidgets.QComboBox(self.tab_3)
        self.ocrmodecombo.setObjectName("ocrmodecombo")
        self.ocrmodecombo.addItem("")
        self.ocrmodecombo.addItem("")
        self.gridLayout_5.addWidget(self.ocrmodecombo, 1, 5, 1, 1)
        self.qrgridLayout.addLayout(self.gridLayout_5, 0,0)
        self.ocrpic = QtWidgets.QGraphicsView(self.tab_3)
        self.ocrpic.setObjectName("ocrpic")
        self.qrgridLayout.addWidget(self.ocrpic, 1, 0)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_11.addWidget(self.label_14)
        self.digitsequence = QtWidgets.QLineEdit(self.tab_3)
        self.digitsequence.setReadOnly(True)
        self.digitsequence.setObjectName("digitsequence")
        self.horizontalLayout_11.addWidget(self.digitsequence)
        self.qrgridLayout.addLayout(self.horizontalLayout_11, 2, 0)
        self.verticalLayout_13.addLayout(self.qrgridLayout)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_14.addWidget(self.label_17)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.toolsarraylab = QtWidgets.QLabel(self.tab_2)
        self.toolsarraylab.setObjectName("toolsarraylab")
        self.horizontalLayout_9.addWidget(self.toolsarraylab)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.leftrightconversion = QtWidgets.QPushButton(self.tab_2)
        self.leftrightconversion.setObjectName("leftrightconversion")
        self.verticalLayout_18.addWidget(self.leftrightconversion)
        self.rightleftconversion = QtWidgets.QPushButton(self.tab_2)
        self.rightleftconversion.setObjectName("rightleftconversion")
        self.rightleftconversion.setEnabled(False)
        self.verticalLayout_18.addWidget(self.rightleftconversion)
        self.horizontalLayout_9.addLayout(self.verticalLayout_18)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.toolspicturelab = QtWidgets.QLabel(self.tab_2)
        self.toolspicturelab.setObjectName("toolspicturelab")
        self.verticalLayout_22.addWidget(self.toolspicturelab)
        self.horizontalLayout_9.addLayout(self.verticalLayout_22)
        self.verticalLayout_17.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.arraybrows = QtWidgets.QPlainTextEdit(self.tab_2)
        self.arraybrows.setObjectName("arraybrows")
        self.arfont = self.arraybrows.font()
        self.arfont.setPointSize(14)
        self.arraybrows.setFont(self.arfont)
        self.horizontalLayout_10.addWidget(self.arraybrows)
        self.conversiongridLayout = QtWidgets.QGridLayout()
        self.conversiongridLayout.setObjectName("conversiongridLayout")
        self.Imageconvvisualizer = QtWidgets.QGraphicsView(self.tab_2)
        self.Imageconvvisualizer.setObjectName("Imageconvvisualizer")
        self.conversiongridLayout.addWidget(self.Imageconvvisualizer, 0,0)
        self.toolsloadimgpush = QtWidgets.QPushButton(self.tab_2)
        self.toolsloadimgpush.setObjectName("toolsloadimgpush")
        self.conversiongridLayout.addWidget(self.toolsloadimgpush, 1,0)
        self.horizontalLayout_10.addLayout(self.conversiongridLayout)
        self.verticalLayout_17.addLayout(self.horizontalLayout_10)
        self.verticalLayout_14.addLayout(self.verticalLayout_17)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.tabWidget.setCurrentIndex(0)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def clearterminal(self):
        self.logbrowser.clear()
        self.logbrowser.update()

    def showterminal(self, text):
        self.logbrowser.setReadOnly(False)
        self.logbrowser.setPlainText(text)
        scrolling = self.logbrowser.verticalScrollBar()
        scrolling.setValue(scrolling.maximum())
        self.logbrowser.setReadOnly(True)
        self.logbrowser.update()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Neural Network Visualizer - Mark Diamantino Caribé"))
        self.trainingsetbox.setItemText(0, _translate("Dialog", "Big (60000)"))
        self.trainingsetbox.setItemText(1, _translate("Dialog", "Small (2000)"))
        self.trainingsetbox.setItemText(2, _translate("Dialog", "Tiny (100)"))
        self.anothertestcheck.setText(_translate("Dialog", "Different Testset ?"))
        self.testsetbox.setItemText(0, _translate("Dialog", "Small (2000)"))
        self.testsetbox.setItemText(1, _translate("Dialog", "Tiny (100)"))
        self.testsetbox.setItemText(2, _translate("Dialog", "Big (60000)"))
        self.datasetlabel.setText(_translate("Dialog", "Dataset"))
        self.trainingtestlabel.setText(_translate("Dialog", "Trainingset / Testset Ratio"))
        self.activationlabel.setText(_translate("Dialog", "Activation Function"))
        self.activationbox.setItemText(0, _translate("Dialog", "Soft Sign"))
        self.activationbox.setItemText(1, _translate("Dialog", "Arctan"))
        self.activationbox.setItemText(2, _translate("Dialog", "Tanh (Hyperbolic tangent)"))
        self.activationbox.setItemText(3, _translate("Dialog", "Logistic (Sigmoid)"))
        self.lratelabel.setText(_translate("Dialog", "Learning Rate"))
        self.weightsinlabel.setText(_translate("Dialog", "Weights init."))
        self.hiddenlabel.setText(_translate("Dialog", "H"))
        self.crossvalabel.setText(_translate("Dialog", "Cross-Validations"))
        self.trainingepochslab.setText(_translate("Dialog", "Training Epochs"))
        self.dodropcheck.setText(_translate("Dialog", "Do Dropout ?"))
        self.saveweightscheck.setText(_translate("Dialog", "Save Weights ?"))
        self.loadwegithsb.setText(_translate("Dialog", "Load Weights"))
        self.startbutton.setText(_translate("Dialog", "Start"))
        self.pausebutton.setText(_translate("Dialog", "Pause"))
        self.labelivelogs.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Live logs</span></p></body></html>"))
        self.labelconfusionmat.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Confusion Matrix</span></p></body></html>"))
        self.savelogscheck.setText(_translate("Dialog", "Do you want to save logs ?"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Standard"))
        self.ocruploadpushbutton.setText(_translate("Dialog", "Load Picture"))
        self.startocrpushbutton.setText(_translate("Dialog", "Start OCR ( will train first to have weights )"))
        self.ocrndigilabel.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt;\">Number of digits in picture</span></p></body></html>"))
        self.ocrmodelabel.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt;\">OCR mode</span></p></body></html>"))
        self.ocrmodecombo.setItemText(0, _translate("Dialog", "Automatic ( more then one digit )"))
        self.ocrmodecombo.setItemText(1, _translate("Dialog", "Manual ( one digit at a time )"))
        self.label_14.setText(_translate("Dialog", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt; font-weight:600;\">Sequence of digits :</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "OCR "))
        self.label_17.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Array/Image converter</span></p></body></html>"))
        self.toolsarraylab.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Array </span><span style=\" font-size:10pt;\">( [0....783] )</span></p></body></html>"))
        self.leftrightconversion.setText(_translate("Dialog", ">>>   CONVERT to greyscale image >>>"))
        self.rightleftconversion.setText(_translate("Dialog", "<<<  CONVERT to MNIST format <<<"))
        self.toolspicturelab.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Picture</span></p></body></html>"))
        self.toolsloadimgpush.setText(_translate("Dialog", "Load Image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Tools"))
